version: '3.8'

services:
  discovery-server:
    image: ${DOCKER_USERNAME}/discovery-server:${IMAGE_TAG:-latest}
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - clyvasync-net
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8761 || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s

  identity-service:
    image: ${DOCKER_USERNAME}/identity-service:${IMAGE_TAG:-latest}
    container_name: identity-service
    environment:
      - DBMSRSQL_CONNECTION=jdbc:postgresql://clyvasync-postgres:5432/clyvasync_network
      - USERNAME_RSQL=${USERNAME_RSQL}
      - PASSWORD_RSQL=${PASSWORD_RSQL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-clyvasync:9092
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - REDIS_CONNECTION=clyvasync-redis
      - PASSWORD_REDIS=${PASSWORD_REDIS}
      - PASSWORD_PEPPER=${PASSWORD_PEPPER}
      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
    networks:
      - clyvasync-net
    depends_on:
      discovery-server:
        condition: service_healthy

  profile-service:
    image: ${DOCKER_USERNAME}/profile-service:${IMAGE_TAG:-latest}
    container_name: profile-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://clyvasync-postgres:5432/clyvasync_profile_db
      - SPRING_DATASOURCE_USERNAME=${USERNAME_RSQL}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD_RSQL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-clyvasync:9092
      - REDIS_CONNECTION=clyvasync-redis
      - PASSWORD_REDIS=${PASSWORD_REDIS}
      - IDENTITY_SERVER_URL=http://identity-service:8081
    networks:
      - clyvasync-net
    depends_on:
      discovery-server:
        condition: service_healthy

  media-service:
    image: ${DOCKER_USERNAME}/media-service:${IMAGE_TAG:-latest}
    container_name: media-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://clyvasync-postgres:5432/clyvasync_photo_db
      - SPRING_DATASOURCE_USERNAME=${USERNAME_RSQL}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD_RSQL}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-clyvasync:9092
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - BUCKET_NAME=${BUCKET_NAME}
      - REDIS_CONNECTION=clyvasync-redis
      - PASSWORD_REDIS=${PASSWORD_REDIS}
      - IDENTITY_SERVER_URL=http://identity-service:8081
    networks:
      - clyvasync-net
    depends_on:
      discovery-server:
        condition: service_healthy

  gateway-service:
    image: ${DOCKER_USERNAME}/gateway-service:${IMAGE_TAG:-latest}
    container_name: gateway-service
    ports:
      - "8443:8443"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_REDIS_HOST=clyvasync-redis
    networks:
      - clyvasync-net
    depends_on:
      discovery-server:
        condition: service_healthy

networks:
  clyvasync-net:
    external: true
    name: clyvasync-net