server:
  port: 8085
  forward-headers-strategy: framework
spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5432/clyvasync_photo_db
    username: ${USERNAME_RSQL}
    password: ${PASSWORD_RSQL}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://localhost:8443/identity-service/oauth2/jwks
          issuer-uri: https://localhost:8443/identity-service

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # KAFKA PHẢI NẰM Ở ĐÂY (Dưới spring)
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}

    # --- CẤU HÌNH CHO BÊN GỬI (PRODUCER) ---
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false # Tắt cái này để Media Service dễ nhận diện event hơn

    # --- CẤU HÌNH CHO BÊN NHẬN (CONSUMER) ---
    consumer:
      group-id: media-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: "com.commoncore.dto.event.BaseEvent"
        spring.json.trusted.packages: "com.commoncore.dto.event, com.commoncore.dto"

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 1000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson2
      valueEncoder: java
      valueDecoder: java
      uri: redis://:${PASSWORD_REDIS}@${REDIS_CONNECTION:localhost}:6379/
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  server-url: https://localhost:8443/media-service

aws:
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    bucket-name: ${BUCKET_NAME}