package com.commoncore.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ResultCode {
    SUCCESS(1000, HttpStatus.OK),
    FAILED(9000, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 1xxx: Authentication & Authorization ---
    UNAUTHENTICATED(1001, HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(1002, HttpStatus.FORBIDDEN),
    TOKEN_EXPIRED(1003, HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(1004, HttpStatus.UNAUTHORIZED),
    LOGIN_FAILED(1005, HttpStatus.UNAUTHORIZED),
    USER_NOT_ACTIVE(1006, HttpStatus.FORBIDDEN),
    USER_ALREADY_ACTIVE(1007, HttpStatus.BAD_REQUEST),
    LOGOUT_SUCCESS(1008, HttpStatus.OK),
    LOGOUT_FAILED(1009, HttpStatus.INTERNAL_SERVER_ERROR),
    ACCOUNT_TEMPORARILY_LOCKED(1010, HttpStatus.FORBIDDEN),
    DEVICE_NOT_FOUND(1011, HttpStatus.NOT_FOUND),

    // --- 2xxx: User & Profile Management (Success & Specific) ---
    REGISTER_SUCCESS(2010, HttpStatus.CREATED),
    ACTIVATION_SUCCESS(2011, HttpStatus.OK),
    PASSWORD_RESET_SUCCESS(2012, HttpStatus.OK),
    PASSWORD_CHANGED_SUCCESS(2013, HttpStatus.OK),
    EMAIL_VERIFICATION_SENT(2014, HttpStatus.OK),

    // --- 11xx: Verification (OTP / Captcha) ---
    OTP_INVALID(1101, HttpStatus.BAD_REQUEST),
    OTP_EXPIRED(1102, HttpStatus.BAD_REQUEST),
    OTP_VALID(1103, HttpStatus.OK),
    CAPTCHA_REQUIRED(1104, HttpStatus.BAD_REQUEST),
    CAPTCHA_INVALID(1105, HttpStatus.BAD_REQUEST),
    EMAIL_IS_SPAM(1106, HttpStatus.BAD_REQUEST),
    PLEASE_WAIT_BEFORE_RESENDING(1107, HttpStatus.TOO_MANY_REQUESTS),
    OTP_REQUIRED(1108, HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1109, HttpStatus.BAD_REQUEST),

    // --- 2xxx: User & Profile Management ---
    USER_NOT_FOUND(2001, HttpStatus.NOT_FOUND),
    USER_EXISTED(2002, HttpStatus.BAD_REQUEST),
    EMAIL_ALREADY_USED(2003, HttpStatus.BAD_REQUEST),
    USERNAME_INVALID(2004, HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(2005, HttpStatus.BAD_REQUEST),
    PASSWORD_TOO_WEAK(2006, HttpStatus.BAD_REQUEST),
    PASSWORD_NOT_MATCH(2007, HttpStatus.BAD_REQUEST),
    CURRENT_PASSWORD_INCORRECT(2008, HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_SAME_AS_OLD(2009, HttpStatus.BAD_REQUEST),

    // --- 3xxx: Post & Content ---
    POST_NOT_FOUND(3001, HttpStatus.NOT_FOUND),
    CANNOT_DELETE_POST(3002, HttpStatus.FORBIDDEN),
    CANNOT_EDIT_POST(3003, HttpStatus.FORBIDDEN),
    CONTENT_TOO_LONG(3004, HttpStatus.BAD_REQUEST),

    // --- 4xxx: Messaging & Chat ---
    MESSAGE_NOT_FOUND(4001, HttpStatus.NOT_FOUND),
    MESSAGE_NOT_OWNER(4002, HttpStatus.FORBIDDEN),
    MESSAGE_RECALL_EXPIRED(4003, HttpStatus.BAD_REQUEST),
    MESSAGE_ALREADY_RECALLED(4004, HttpStatus.BAD_REQUEST),
    CANNOT_SEND_TO_SELF(4005, HttpStatus.BAD_REQUEST),
    MESSAGE_ACCESS_DENIED(4006, HttpStatus.FORBIDDEN),

    // --- 5xxx: Social & Relationships ---
    ALREADY_FRIENDS(5001, HttpStatus.BAD_REQUEST),
    FRIEND_REQUEST_NOT_FOUND(5002, HttpStatus.NOT_FOUND),
    USER_BLOCKED(5003, HttpStatus.BAD_REQUEST),
    CANNOT_PERFORM_ON_SELF(5004, HttpStatus.BAD_REQUEST),
    BLOCK_NOT_FOUND(5005, HttpStatus.NOT_FOUND),
    CANNOT_BLOCK_ADMIN(5006, HttpStatus.FORBIDDEN),
    ALREADY_BLOCKED(5007, HttpStatus.BAD_REQUEST),
    BLOCKED_BY_USER(5008, HttpStatus.FORBIDDEN),
    INTERACTION_RESTRICTED(5009, HttpStatus.FORBIDDEN),
    BLOCK_SUCCESS(5010, HttpStatus.OK),
    UNBLOCK_SUCCESS(5011, HttpStatus.OK),

    // --- 6xxx: Media & Infrastructure ---
    FILE_TOO_LARGE(6001, HttpStatus.BAD_REQUEST),
    UNSUPPORTED_FILE_TYPE(6002, HttpStatus.BAD_REQUEST),
    UPLOAD_FAILED(6003, HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_NOT_FOUND(6004, HttpStatus.INTERNAL_SERVER_ERROR),
    RINGTONE_NOT_FOUND(6005, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 7xxx: Comments & Interactions ---
    COMMENT_NOT_FOUND(7001, HttpStatus.NOT_FOUND),
    COMMENT_NOT_OWNER(7002, HttpStatus.FORBIDDEN),
    CANNOT_EDIT_COMMENT(7003, HttpStatus.FORBIDDEN),
    CANNOT_DELETE_COMMENT(7004, HttpStatus.FORBIDDEN),
    COMMENT_CONTENT_TOO_LONG(7005, HttpStatus.BAD_REQUEST),
    INVALID_REACTION_TYPE(7006, HttpStatus.BAD_REQUEST),
    REACTION_NOT_FOUND(7007, HttpStatus.NOT_FOUND),
    NOTIFICATION_NOT_FOUND(7008, HttpStatus.NOT_FOUND),
    CANNOT_ACCESS_NOTIFICATION(7009, HttpStatus.FORBIDDEN),

    // --- 8xxx: Validation Errors ---
    INVALID_EMAIL(8001, HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(8002, HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(8003, HttpStatus.BAD_REQUEST),
    PASSWORD_MIN_8_CHARACTERS(8004, HttpStatus.BAD_REQUEST),
    USERNAME_REQUIRED(8005, HttpStatus.BAD_REQUEST),
    FIELD_REQUIRED(8006, HttpStatus.BAD_REQUEST),
    INVALID_INPUT(8007, HttpStatus.BAD_REQUEST),
    USERNAME_LENGTH_INVALID(8008, HttpStatus.BAD_REQUEST),
    CONFIRM_PASSWORD_REQUIRED(8009, HttpStatus.BAD_REQUEST),
    BIRTHDATE_MUST_BE_IN_PAST(8010, HttpStatus.BAD_REQUEST),

    // --- 9xxx: Global / System ---
    INVALID_REQUEST_FORMAT(9001, HttpStatus.BAD_REQUEST),
    INVALID_KEY(9002, HttpStatus.BAD_REQUEST),
    UPDATE_FAILED(9003, HttpStatus.INTERNAL_SERVER_ERROR),
    DELETE_FAILED(9004, HttpStatus.INTERNAL_SERVER_ERROR),
    CREATE_FAILED(9005, HttpStatus.INTERNAL_SERVER_ERROR),
    DATABASE_ERROR(9006, HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_SERVER_ERROR(9007, HttpStatus.INTERNAL_SERVER_ERROR),
    UNCATEGORIZED_EXCEPTION(9999, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 10xxx: Reels & Short Videos ---
    REEL_NOT_FOUND(10001, HttpStatus.NOT_FOUND),
    REEL_UPLOAD_FAILED(10002, HttpStatus.INTERNAL_SERVER_ERROR),
    REEL_PROCESSING(10003, HttpStatus.ACCEPTED),
    REEL_FILE_INVALID(10004, HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_REEL(10005, HttpStatus.FORBIDDEN),
    REEL_AI_TRAINING_FAILED(10006, HttpStatus.SERVICE_UNAVAILABLE),
    REEL_METADATA_INVALID(10007, HttpStatus.BAD_REQUEST),

    // --- 11xxx: Stories (Short-lived Content) ---
    STORY_NOT_FOUND(11001, HttpStatus.NOT_FOUND),
    STORY_EXPIRED(11002, HttpStatus.GONE),
    STORY_UPLOAD_FAILED(11003, HttpStatus.INTERNAL_SERVER_ERROR),
    STORY_TOO_MANY_ITEMS(11004, HttpStatus.BAD_REQUEST),
    CANNOT_VIEW_STORY(11005, HttpStatus.FORBIDDEN),
    STORY_MEDIA_UNSUPPORTED(11006, HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    STORY_REACTION_FAILED(11007, HttpStatus.BAD_REQUEST),

    // --- 12xxx: Groups & Communities ---
    GROUP_NOT_FOUND(12001, HttpStatus.NOT_FOUND),
    GROUP_EXISTED(12002, HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_GROUP(12003, HttpStatus.FORBIDDEN),
    CANNOT_EDIT_GROUP(12004, HttpStatus.FORBIDDEN),
    NOT_A_MEMBER(12005, HttpStatus.FORBIDDEN),
    ALREADY_A_MEMBER(12006, HttpStatus.BAD_REQUEST),
    GROUP_INVITATION_NOT_FOUND(12007, HttpStatus.NOT_FOUND),
    ALREADY_INVITED(12008, HttpStatus.BAD_REQUEST),
    MEMBER_NOT_FOUND(12009, HttpStatus.NOT_FOUND),
    GROUP_ACCESS_DENIED(12010, HttpStatus.FORBIDDEN),
    CANNOT_LEAVE_GROUP_CREATOR(12011, HttpStatus.BAD_REQUEST),
    GROUP_MAX_MEMBERS_REACHED(12012, HttpStatus.BAD_REQUEST),
    INVITATION_EXPIRED(12013, HttpStatus.BAD_REQUEST),
    NOT_AN_ADMIN(12014, HttpStatus.FORBIDDEN),
    CANNOT_INVITE_SELF(12015, HttpStatus.BAD_REQUEST),
    INVITATION_ALREADY_PROCESSED(12016, HttpStatus.GONE),
    INVITATION_NOT_FOUND(12017, HttpStatus.NOT_FOUND),
    NOT_AN_INVITEE(12018, HttpStatus.FORBIDDEN),
    JOIN_REQUEST_NOT_FOUND(12019, HttpStatus.NOT_FOUND),
    ALREADY_A_MEMBER_REQUEST_CLEARED(12020, HttpStatus.BAD_REQUEST),
    MEMBER_REMOVAL_FAILED(12021, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 13xxx: Authorization & Permission System ---
    PERMISSION_DENIED(13001, HttpStatus.FORBIDDEN),
    UNAUTHORIZED_ACCESS(13002, HttpStatus.UNAUTHORIZED),
    RESOURCE_OWNER_REQUIRED(13003, HttpStatus.FORBIDDEN),
    SPICEDB_CONNECTION_ERROR(13004, HttpStatus.SERVICE_UNAVAILABLE),
    SPICEDB_WRITE_ERROR(13005, HttpStatus.INTERNAL_SERVER_ERROR),
    SPICEDB_SCHEMA_VIOLATION(13006, HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_INSUFFICIENT(13007, HttpStatus.FORBIDDEN),
    GROUP_MEMBER_REQUIRED(13008, HttpStatus.FORBIDDEN),
    FRIENDSHIP_REQUIRED(13009, HttpStatus.FORBIDDEN),
    PERMISSION_SYNC_PENDING(13010, HttpStatus.ACCEPTED),
    SPICEDB_READ_ERROR(13011, HttpStatus.INTERNAL_SERVER_ERROR),
    PERMISSION_REVC_FAILED(13012, HttpStatus.INTERNAL_SERVER_ERROR);

    private final int code;
    private final HttpStatusCode statusCode;

    ResultCode(int code, HttpStatusCode statusCode) {
        this.code = code;
        this.statusCode = statusCode;
    }
}